### PR TITLE
Tiberiturbureanu branch

### PR DESCRIPTION
**Pull request by tibict**
added firstname lastname tasks

### CODE REVIEW

**Comment by tibict** [comment]
added Tiberiu TUrbureanu tasks

**Review by cristiangfilip — CHANGES_REQUESTED** [review]
Hey Tibi! Everything is ok, you can add me as reviewer

**Comment by PuraAlina97** [comment]
Hey Tibi! All looks good. Add me as reviewer.

**Comment by tibict** [comment]
Cristi and Alina, please check the changes you requested and let me know if you approve them. Thanks!

**Review by cristiangfilip — APPROVED** [review]

**Review by PuraAlina97 — APPROVED** [review]
Everything is ok.

**Pull request merged**
